<?php
/**
 * Implements hook_ds_fields_info().
 */
function rate_display_ds_fields_info($entity_type) {

  // Provide a custom field to display suite
  $fields = array();

  $fields['node']['rate'] = array(
    'title' => t('Rate'),
    'field_type' => DS_FIELD_TYPE_FUNCTION,
    'function' => 'rate_display_ds_field_rate',
  );

  return $fields;
}

function rate_display_ds_field_rate($field) {
   return rate_embed($field['entity'], 'hap_rating_system', RATE_FULL);
}
